### ISSUE TITLE
PNDA docker not found

### ISSUE THREAD

**Issue by bruceforlearn** [pndaproject/pnda#151]
Hello guys,

I want to isntall a PNDA demo on docker
According to this article http://pnda.io/pnda-guide/repos/pnda-package-server-docker/

but it happened error

 [root@localhost pnda]# git clone https://github.com/pndaproject/pnda-package-server-docker
Cloning into 'pnda-package-server-docker'...
Username for 'https://github.com': huanyu135@126.com
Password for 'https://huanyu135@126.com@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/pndaproject/pnda-package-server-docker/' not found

does anyone can help me ?

thank you

**Comment by trsmith2** [comment]
https://github.com/pndaproject/pnda-package-server-docker was deprecated with 3.3, please follow the latest creation guide at http://pnda.io/pnda-guide.

In order that we can keep our docs in order, can I ask whereabouts in our docs you found the link above?

**Comment by bruceforlearn** [comment]
@trsmith2 thank you
I use gooole and search pnda docker with result

**Comment by bruceforlearn** [comment]
@trsmith2  could you please tell me why deprecate the docker with PNDA?
you know I love the container, it's too easy for deployment

**Comment by trsmith2** [comment]
In our case we're delivering only source, so you need to actually build the container first - requiring a Docker installation to do so. Since building these components is typically a 1-off activity there's very little benefit to **forcing** someone to go through the process of installing Docker, which on many common platforms (e.g. Ubuntu 14.04) tends not to 'just work' in our experience. 

Meanwhile we don't **prevent** you from using a container to do this build, our only requirement is Ubuntu 14.04/RHEL7. Feel free to do this in a container if it suits your deployment environment.

**Comment by bruceforlearn** [comment]
@trsmith2 thank you 
I try to use saltstack script to auto-install PNDA platform but failed 
could you please send me PNDA dockerfile?
I'm interesting in PNDA containers and wanna try

**Comment by trsmith2** [comment]
There is no Dockerfile for the current version of the PNDA build. Please use a standard Ubuntu/RHEL image from the Docker repository and follow the instructions I referenced above.

**Comment by bruceforlearn** [comment]
@trsmith2 send me PNDA 3.3 dockerfile, please

**Comment by bruceforlearn** [comment]
I don't want to write dockerfile with PNDA, it's too difficult for me 
hahaha

**Comment by bruceforlearn** [comment]
@trsmith2 SIR,pleaaaaaaaaaase

give 3.2 PNDA dockerfile to me 

thank you very much

**Comment by bruceforlearn** [comment]
@klyr @donaldh @krickwix @91pavan does anyone else have PNDA 3.2 dockerfile?
could you please send me to try it ?

thank you
